// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Game__char_32_State_c4db98e625238cb4abed48cda8fae98eIndex = 0;
		public const int Game__char_32_State__char_32_Reference_1ab61af51f8fd1340afb5b4c00e0954eIndex = 1;
		public const int Civilization__char_32_Soldier__char_32_Variant_b7a82f6c353d52d4397768ab8f734fbcIndex = 2;
		public const int Nature__char_32_Soldier__char_32_Variant_d6a82c87e5905cf4da2d7816df59e943Index = 3;
		public const int Soldier_f8c53656e690229449e63505503f1a5bIndex = 4;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Game__char_32_State_c4db98e625238cb4abed48cda8fae98e", 0 },

			{ "Game__char_32_State__char_32_Reference_1ab61af51f8fd1340afb5b4c00e0954e", 1 },

			{ "Civilization__char_32_Soldier__char_32_Variant_b7a82f6c353d52d4397768ab8f734fbc", 2 },

			{ "Nature__char_32_Soldier__char_32_Variant_d6a82c87e5905cf4da2d7816df59e943", 3 },

			{ "Soldier_f8c53656e690229449e63505503f1a5b", 4 },

		};
	}
}
