// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Player_b0a4b4641720deb4c85a8faaba398bf8Index = 0;
		public const int Soldier_f8c53656e690229449e63505503f1a5bIndex = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Player_b0a4b4641720deb4c85a8faaba398bf8", 0 },

			{ "Soldier_f8c53656e690229449e63505503f1a5b", 1 },

		};
	}
}
