// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Nature__char_32_Soldier__char_32_Variant_WorldTree__char_46_Unit__char_46_Heal_e283d7c7_4ebf_493f_9823_17f79a943783 : IEntityCommand
	{
		public float health;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalNature__char_32_Soldier__char_32_Variant_WorldTree__char_46_Unit__char_46_Heal_e283d7c7_4ebf_493f_9823_17f79a943783;

		public Nature__char_32_Soldier__char_32_Variant_WorldTree__char_46_Unit__char_46_Heal_e283d7c7_4ebf_493f_9823_17f79a943783
		(
			float datahealth
		)
		{
			health = datahealth;
		}

		public static void Serialize(Nature__char_32_Soldier__char_32_Variant_WorldTree__char_46_Unit__char_46_Heal_e283d7c7_4ebf_493f_9823_17f79a943783 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteFloat(commandData.health, FloatMeta.NoCompression());
		}

		public static Nature__char_32_Soldier__char_32_Variant_WorldTree__char_46_Unit__char_46_Heal_e283d7c7_4ebf_493f_9823_17f79a943783 Deserialize(IInProtocolBitStream bitStream)
		{
			var datahealth = bitStream.ReadFloat(FloatMeta.NoCompression());

			return new Nature__char_32_Soldier__char_32_Variant_WorldTree__char_46_Unit__char_46_Heal_e283d7c7_4ebf_493f_9823_17f79a943783
			(
				datahealth
			){};
		}
	}
}
