// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Soldier_WorldTree__char_46_Unit__char_46_Die_6661d113_8f98_49d6_a6f6_fca2d95730eb : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalSoldier_WorldTree__char_46_Unit__char_46_Die_6661d113_8f98_49d6_a6f6_fca2d95730eb;

		public static void Serialize(Soldier_WorldTree__char_46_Unit__char_46_Die_6661d113_8f98_49d6_a6f6_fca2d95730eb commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Soldier_WorldTree__char_46_Unit__char_46_Die_6661d113_8f98_49d6_a6f6_fca2d95730eb Deserialize(IInProtocolBitStream bitStream)
		{

			return new Soldier_WorldTree__char_46_Unit__char_46_Die_6661d113_8f98_49d6_a6f6_fca2d95730eb
			(
			){};
		}
	}
}
